// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMdSwhgpevYYWznusQidZhedL0Ex6ljj4',
    appId: '1:625316552817:web:4ad29d0cfdfb8e297a3bd0',
    messagingSenderId: '625316552817',
    projectId: 'skincare-app-e4f13',
    authDomain: 'skincare-app-e4f13.firebaseapp.com',
    storageBucket: 'skincare-app-e4f13.firebasestorage.app',
    measurementId: 'G-5DPDBYQG8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFBY1Xs9Bo5A4dB9_0X4p_4-102KdVxpA',
    appId: '1:625316552817:android:74ed03db435c7c1c7a3bd0',
    messagingSenderId: '625316552817',
    projectId: 'skincare-app-e4f13',
    storageBucket: 'skincare-app-e4f13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGD8AzwGQxS7kU9dSJYWqBpg3npyxohYA',
    appId: '1:625316552817:ios:0759ad3f36d93f6f7a3bd0',
    messagingSenderId: '625316552817',
    projectId: 'skincare-app-e4f13',
    storageBucket: 'skincare-app-e4f13.firebasestorage.app',
    iosBundleId: 'com.example.skincareApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGD8AzwGQxS7kU9dSJYWqBpg3npyxohYA',
    appId: '1:625316552817:ios:0759ad3f36d93f6f7a3bd0',
    messagingSenderId: '625316552817',
    projectId: 'skincare-app-e4f13',
    storageBucket: 'skincare-app-e4f13.firebasestorage.app',
    iosBundleId: 'com.example.skincareApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMdSwhgpevYYWznusQidZhedL0Ex6ljj4',
    appId: '1:625316552817:web:1104f6181c736bdd7a3bd0',
    messagingSenderId: '625316552817',
    projectId: 'skincare-app-e4f13',
    authDomain: 'skincare-app-e4f13.firebaseapp.com',
    storageBucket: 'skincare-app-e4f13.firebasestorage.app',
    measurementId: 'G-9GET3TM7L2',
  );
}
